### ISSUE TITLE
Need method to fetch deployment info of `metadata cell` on CKB

### ISSUE THREAD

**Issue by ashuralyk** [axonweb3/axon#1501] opened 2023-10-26 01:42 UTC
context: https://discord.com/channels/674518700518408213/1173534867296895006/1173534872044843039

**Comment by KaoImin** [comment] 2023-11-01 02:04
The deployment info of metadata cell is stored in metadata system contract. Firstly, it should be set by a transaction, and then you can call the [`axon_getCkbRelatedInfo`](https://github.com/axonweb3/axon/issues/1505) rpc method to get them.

**Comment by wenyuanhust** [comment] 2023-11-06 04:45
I refers to metadata contract as the one which are responsible for managing the metadata cell on ckb of Axon-based chain.
So,for metadata cell:  
- the code hash  is type id of metadata contract
- the hash type should be type
- the args is metadata_type_id of CkbRelatedInfo which can be got from axon_getCkbRelatedInfo   
For ckb testnet, the type id of metadata contract can be got from [axon-contracts-testnet-address-info](https://github.com/cryptape/layer2-internal/wiki/axon-contracts-testnet-address-info) under section metadata.

**Comment by Flouse** [comment] 2023-11-13 08:02
> * the args is metadata_type_id of CkbRelatedInfo which can be got from axon_getCkbRelatedInfo

Test `CkbRelatedInfo` on axon-alphanet

```bash
curl --location --request POST 'https://rpc-alphanet-axon.ckbapp.dev/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "axon_getCkbRelatedInfo",
    "params": []
}'
```

## Result: None CKB related info
```js
{"jsonrpc":"2.0","error":{"code":-49999,
"message":"Internal error",
"data":"[ProtocolError] Kind: Executor, Error: None CKB related info"},
"id":42}%             
```

**Comment by Flouse** [comment] 2023-11-13 08:05
初步判断 metadata cell 的前置创建工作未实施，需提供更清晰的指引给 @ashuralyk 

经与 @wenyuanhust 沟通，由 wenyuan 梳理 metadata cell 的创建和更新流程，并推进相关测试。

cc @blckngm ，~~因为如何将 `IBCHandler 的地址放到 metadata cell 里的 lock args 里`，需要进一步沟通确认。~~

**Comment by blckngm** [comment] 2023-11-13 08:22
The `IBCHandler` address is to be put in ibc cell (connection/channel) lock args, not metadata lock args. So it's not a concern for the metadata cell.

**Comment by wenyuanhust** [comment] 2023-11-17 07:24
steps:
1. Create an unique metadata cell. 
    As ckb-cli can not calculate type id, ckb-sdk-rust can only calculate type id for TYPE_ID.
    So I calculate type_id of metadata cell manually in axon-contract repo.  
>> tx-hash:  0xa2a2d631aa974ceb48db92fed774ca73f2a976c12d50f1beb64a516025f3cb6f
      index: 0
      cell type_script:  
"code_hash": 0x2c8f63ac17c1e5e660dddbf49e88994cd1c49d4d6e99e7a7fd3f8879700d3cd1  
"hash_type": type  
"args": 0xdb0782aba62896c2a7c279f3de8dbbd7fd06729cc8b7b499df93f5c450f61839  

2. Send a tx to set CkbRelatedInfo for system contract METADATA_CONTRACT_ADDRESS.
    I'm using hardhat to do this job, I now can send tx to alpha net, but the tx failed.
    This is the infos in axon explorer:   
>> Transaction Hash  0xdba17b9d8ae445327a6b479ecc6527bb048651edcae13eeb8271dec1cd10e1c7
      Result   Error: (Awaiting internal transactions for reason)
      Status   Confirmed

**Comment by ashuralyk** [comment] 2023-11-20 04:06
@wenyuanhust I just want metadata cell's type script info, including its `code_hash` and `args`, I need to write them into config file of forcerelay to search on-chain metadata cell for light client verification use

**Comment by wenyuanhust** [comment] 2023-11-20 08:23
> steps:
> 
> 1. Create an unique metadata cell.
>    As ckb-cli can not calculate type id, ckb-sdk-rust can only calculate type id for TYPE_ID.
>    So I calculate type_id of metadata cell manually in axon-contract repo.
> 
> > > tx-hash:  0xa2a2d631aa974ceb48db92fed774ca73f2a976c12d50f1beb64a516025f3cb6f
> > > index: 0
> > > cell type_script:
> > > "code_hash": 0x2c8f63ac17c1e5e660dddbf49e88994cd1c49d4d6e99e7a7fd3f8879700d3cd1
> > > "hash_type": type
> > > "args": 0xdb0782aba62896c2a7c279f3de8dbbd7fd06729cc8b7b499df93f5c450f61839
> 
> 2. Send a tx to set CkbRelatedInfo for system contract METADATA_CONTRACT_ADDRESS.
>    I'm using hardhat to do this job, I now can send tx to alpha net, but the tx failed.
>    This is the infos in axon explorer:
> 
> > > Transaction Hash  0xdba17b9d8ae445327a6b479ecc6527bb048651edcae13eeb8271dec1cd10e1c7
> > > Result   Error: (Awaiting internal transactions for reason)
> > > Status   Confirmed

@ashuralyk this is the infos about a sample metadata cell. The meatadata only contains 1 validator, with bls_key ( [0u8; 48] ).
I will modify it to the bls_keys of axon-alphanet if necessary.

**Comment by KaoImin** [comment] 2023-11-23 03:12
The issue is fixed in #1576

**Comment by Flouse** [comment] 2023-11-23 03:36
### metadata cell's deployment doc by @wenyuanhust 
https://www.notion.so/cryptape/metadata-cell-info-a9278ba5aac34a16939f6c8d34dde1d5

## Please review
- [ ] @KaoImin 
- [ ] @ashuralyk 
- [x] @blckngm

**Comment by blckngm** [comment] 2023-12-18 04:16
Forcerelay doesn't need to get metadata cell info from axon system contract. Ibc ckb contracts would have no way to verify that the metadata cell is the same as in axon system contract. It only needs to know the type script of the metadata cell. The validity of the metadata cell must be verified by end users offchain.

For forcerelay, it's also not necessary that the metadata cell uses the metadata contract (as type script). The metadata cell could be a normal type-id cell, locked by e.g. multisig.

**Comment by blckngm** [comment] 2023-12-18 04:42
What's the specific documentation work needed here? Deploying metadata cell or setting/fetching deployment info of metadata cell?

**Closed as completed** 2023-12-18 06:48 UTC
Labels: t:feature, document, P-Medium

**Comment by Flouse** [comment] 2023-12-18 06:51
> Forcerelay doesn't need to get metadata cell info from axon system contract. Ibc ckb contracts would have no way to verify that the metadata cell is the same as in axon system contract. It only needs to know the type script of the metadata cell. The validity of the metadata cell must be verified by end users offchain.

If the Axon election feature is not activated, I think you are right. Forcerelay doesn't need [axon-contract/metadata contract](https://github.com/axonweb3/axon-contract/blob/b82a843b36a5565524a14a537a5dbe393e26ca65/contracts/metadata/src/entry.rs#L44-L107)
> [forcerelay-ckb-contracts](https://github.com/synapseweb3/forcerelay-ckb-contracts) only need to know the type script of the metadata cell. The validity of the metadata cell must be verified by end users offchain.

But how? I think we need to leave a simple guide docs telling the end users how to verify it.

## Related Code
- https://github.com/synapseweb3/forcerelay-ckb-contracts/blob/379911be5545b488ecc36ca399f402dc729265c9/contracts/ics/base/src/utils.rs#L138
- https://github.com/synapseweb3/forcerelay-ckb-sdk/blob/59d5e92ee3efe2e260bbbbcba2b926e79b063dd2/src/search.rs#L319-L330
- [axon_metadata_type_script config in e2e/schedule/sdk.config.toml](https://github.com/synapseweb3/forcerelay/blob/c7bb87ca7c84fb6a2a7e29813f66ea83bde47246/e2e/schedule/sdk.config.toml#L14C2-L17)

**Comment by Flouse** [comment] 2023-12-18 06:54
> What's the specific documentation work needed here? Deploying metadata cell or setting/fetching deployment info of metadata cell?

I think all we need now is the docs explaining how to create an Axon metadata cell.
The metadata cell will be used by Forcerealy.
And maybe adding a simple guide explaining how to verify it offline would be better.

**Comment by blckngm** [comment] 2023-12-18 07:08
> But how? I think we need to leave a simple guide docs telling the end users how to verify it.

Assuming the metadata cell is a normal type-id cell (that doesn't use metadata contract), the user would need to verify two things:

* the validators in the metadata cell is the same as the axon chain.

  The metadata cli can provide a `parse-data` sub-command that displays validators in a metadata cell data. (The reverse of `get-data`)

* the cell is locked by a party that he trusts, so the validators wouldn't be changed to someone else.

**Comment by Flouse** [comment] 2023-12-18 07:17
> * the validators in the metadata cell is the same as the axon chain.
>   The metadata cli can provide a `parse-data` sub-command that displays validators in a metadata cell data. (The reverse of `get-data`)
> * the cell is locked by a party that he trusts, so the validators wouldn't be changed to someone else.

LGTM, one more thing, tell the Forcerealy maintainer about [the axon_metadata_type_script config](https://github.com/synapseweb3/forcerelay/blob/c7bb87ca7c84fb6a2a7e29813f66ea83bde47246/e2e/schedule/sdk.config.toml#L14C2-L17)? 
Or add comments for `axon_metadata_type_script config`, leave a link pointing to the metadata deployment docs.

**Comment by ashuralyk** [comment] 2023-12-18 07:22
no need to fetch metadata cell from an official rpc method, but we really need the type script of it as the config value for forcerelay, so the question is how to get this type script

**Comment by wenyuanhust** [comment] 2023-12-18 08:52
> > Forcerelay doesn't need to get metadata cell info from axon system contract. Ibc ckb contracts would have no way to verify that the metadata cell is the same as in axon system contract. It only needs to know the type script of the metadata cell. The validity of the metadata cell must be verified by end users offchain.
> 
> If the Axon election feature is not activated, I think you are right. Forcerelay doesn't need [axon-contract/metadata contract](https://github.com/axonweb3/axon-contract/blob/b82a843b36a5565524a14a537a5dbe393e26ca65/contracts/metadata/src/entry.rs#L44-L107)
> 
> > [forcerelay-ckb-contracts](https://github.com/synapseweb3/forcerelay-ckb-contracts) only need to know the type script of the metadata cell. The validity of the metadata cell must be verified by end users offchain.
> 
> But how? I think we need to leave a simple guide docs telling the end users how to verify it.
> 
> ## Related Code
> * https://github.com/synapseweb3/forcerelay-ckb-contracts/blob/379911be5545b488ecc36ca399f402dc729265c9/contracts/ics/base/src/utils.rs#L138
> * https://github.com/synapseweb3/forcerelay-ckb-sdk/blob/59d5e92ee3efe2e260bbbbcba2b926e79b063dd2/src/search.rs#L319-L330
> * [axon_metadata_type_script config in e2e/schedule/sdk.config.toml](https://github.com/synapseweb3/forcerelay/blob/c7bb87ca7c84fb6a2a7e29813f66ea83bde47246/e2e/schedule/sdk.config.toml#L14C2-L17)

If you fetch metadata type id by axon_getCkbRelatedInfo, it means you trust the axon node. There will be no need to verify the data in the corresponding metadata cell. You get the validators by parsing metadata cell data.
Of course, if you get validators by following GuanHao's suggestion, it is ok with forcerelay.
